[package]
name = "bt-sensor"
version = "0.1.0"
authors = ["Janne Alatalo <alatalo.janne@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
dbus = "0.6.1"
log = "0.4"
env_logger = "0.5.3"
docopt = "1"
serde_json = "1.0"
base64 = "0.9"
